### PR TITLE
Filter path markers

### PR DESCRIPTION
**Pull request by olliewalsh**
Latest coverage planner adds other marker types/actions. Just used those where action is ADD and type is LINE

### CODE REVIEW

**Review by cedbossneo — APPROVED** [review]

**Comment by karlranseierausrom** [comment]
I restarted gui.service , I think it downloaded the changes, because of the line 
```Apr 27 12:40:19 openmower podman[14490]: 485bdc5dec0b21e3f869c1e0a1a04c8c5f57d88113e31ef14b9bacb2acd724e4```
. Still I do have errors. I see the map loading, I see the areas and than the following error appears:
```
Unexpected Application Error!
q.Points is null

$Ee/</<@http://192.168.178.80:4006/assets/index-7a47a275.js:677:149375
$Ee/<@http://192.168.178.80:4006/assets/index-7a47a275.js:677:149350
Hb@http://192.168.178.80:4006/assets/index-7a47a275.js:69:24283
Dd@http://192.168.178.80:4006/assets/index-7a47a275.js:69:42408
QK/<@http://192.168.178.80:4006/assets/index-7a47a275.js:69:40723
O@http://192.168.178.80:4006/assets/index-7a47a275.js:54:1564
A@http://192.168.178.80:4006/assets/index-7a47a275.js:54:1930

```

**Comment by karlranseierausrom** [comment]
Again I received Error Messages after These Changes. 
As soon as the pathes are loaded: 
```Unexpected Application Error!
Cannot read properties of null (reading 'map')
TypeError: Cannot read properties of null (reading 'map')
    at http://192.168.178.80:4006/assets/index-7a47a275.js:677:149384
    at Array.forEach (<anonymous>)
    at http://192.168.178.80:4006/assets/index-7a47a275.js:677:149350
    at Hb (http://192.168.178.80:4006/assets/index-7a47a275.js:69:24283)
    at Dd (http://192.168.178.80:4006/assets/index-7a47a275.js:69:42406)
    at NM (http://192.168.178.80:4006/assets/index-7a47a275.js:69:36624)
    at Uc (http://192.168.178.80:4006/assets/index-7a47a275.js:67:3279)
    at qu (http://192.168.178.80:4006/assets/index-7a47a275.js:69:37185)
    at Zi.flushSync (http://192.168.178.80:4006/assets/index-7a47a275.js:69:56332)
    at Object.N [as setLastMessage] (http://192.168.178.80:4006/assets/index-7a47a275.js:661:18906)```

**Comment by olliewalsh** [comment]
Need to run `podman pull ghcr.io/cedbossneo/openmower-gui:master` then restart

**Comment by olliewalsh** [comment]
Or `podman auto-update` should work too, then restart the service

**Comment by karlranseierausrom** [comment]
Thanks. I thought I did an update. Sorry for that. Now I am on issue https://github.com/cedbossneo/openmower-gui/issues/35 .;-)

**Pull request merged**
